minor script for testing
swecc-uw/swecc-server pull request #45
Opened 2024-11-18 00:27 UTC by kipiiler

2024-11-18 01:17 UTC, elimelt commented
probably better to rewrite these to call the admin commands

2024-11-18 01:21 UTC, elimelt requested changes
you should use django management commands for all scripting since it lets you interact with our domain objects instead of writing raw sql, and is cross platform by default. I've already written both of these as python management commands, but if you want to add a windows stub to all of these to make it easier to trigger then feel free

2024-11-18 01:21 UTC, elimelt commented on scripts/windows/addAllToPool.bat
> +docker exec -it swecc-server-db-1 psql -U root postgres -c "%SQL_QUERY%"
can do this without sql so it also works in prod (not that we should ever run this in prod)

```bash
container_id=$1
cmd="put_all_users_in_pool"
docker exec -it $container_id python server/manage.py $cmd
```

or w/e it is.

2024-11-18 01:21 UTC, elimelt commented on scripts/windows/listUser.bat
> +set "SQL_QUERY= select id, username from members_user"
same here. we also have a list users admin command

2024-11-27 02:16 UTC, ShawnCollinge commented
@elimelt we can close this since your admin dashboard does this right?

2024-11-30 21:53 UTC, closed without merging